name = "chess-game-notes-ws-server"
main = "./src/cf-worker/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[durable_objects.bindings]]
name = "AUTH_REGISTRY"
class_name = "AuthRegistry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer", "AuthRegistry"]

[vars]
# should be set via CF dashboard (as secret)
# JWT_SECRET = "your-jwt-secret-key-here"
